openapi: 3.0.1
info:
  title: Sample Swagger Specification
  version: 1.0.0
  description: "A sample Swagger specification for testing"
paths:
  /hello:
    get:
      responses:
        '200':
          description: ''
      summary: ''
      x-auth-type: None
      x-throttling-tier: Unlimited
x-wso2-production-endpoints:
  urls:
  # - https://swapi.dev/api/
  - https://mtls-demo:8243
