info:
  title: "MTLS test"
  version: "1.0.0"
  description: "MTLS test"
openapi: 3.0.1
paths:
  /hello:
    get:
      responses:
        '200':
          description: "A successful response"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
                    example: "Hello, world!"
